application: muchos-mineros-leaderboards
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: leaderboards.application
libraries:
- name: webapp2
  version: latest
